using KarmaloopAIMLBot;
using KarmaloopAIMLBotServer.Skills;
using System;
using System.Net.Sockets;
using System.Text;
using System.Threading;

namespace KarmaloopAIMLBotServer
{
    /// <summary>
    /// Handles each incomming client request separately.
    /// </summary>
	public class KarmaloopClient
    {
        #region Properties
        /// <summary>
        /// Socket of the client
        /// </summary>
        TcpClient clientSocket { get; set; }

        /// <summary>
        /// Index of the client.
        /// </summary>
        string clNo { get; set; }

        #endregion

        #region Methods
        /// <summary>
        /// Starts an individual client connection
        /// </summary>
        /// <param name="inClientSocket"></param>
        /// <param name="clientNo"></param>
        public void StartClient(TcpClient inClientSocket, string clientNo)
        {
            this.clientSocket = inClientSocket;
            this.clNo = clientNo;
            Thread ctThread = new Thread(HandleChat);
            ctThread.Start();
        }

        /// <summary>
        /// Generates a response for client input sentence.
        /// </summary>
        /// <param name="dataFromClient"></param>
        /// <returns>Response generated by AIML Bot engine</returns>
        protected string ProcessRequestResponse(string dataFromClient)
        {
            Result res = Server.ActiveBot.Chat(new Request(dataFromClient, Server.DefaultUser, Server.ActiveBot));
            string responseStatement = SkillsRepository.Instance.ProcessSkills(res.Output);
            

            return responseStatement;
        }

        /// <summary>
        /// This method handles the chat and runs on a separate thread for each user/client.
        /// </summary>
        private void HandleChat()
        {
            int requestCount = 0;
            byte[] bytesFrom = new byte[10025];
            string dataFromClient = null;
            Byte[] sendBytes = null;
            string serverResponse = null;
            string rCount = null;
            requestCount = 0;

            try
            {
                requestCount = requestCount + 1;
                NetworkStream networkStream = clientSocket.GetStream();
                networkStream.Read(bytesFrom, 0, 10000);
                dataFromClient = System.Text.Encoding.ASCII.GetString(bytesFrom);
                dataFromClient = dataFromClient.Substring(0, dataFromClient.IndexOf("$"));
                Console.WriteLine(" >> " + "From client-" + clNo + dataFromClient);

                rCount = Convert.ToString(requestCount);
                serverResponse = ProcessRequestResponse(dataFromClient);
                sendBytes = Encoding.ASCII.GetBytes(serverResponse);
                networkStream.Write(sendBytes, 0, sendBytes.Length);
                networkStream.Flush();
                Console.WriteLine(" >> " + serverResponse);
                clientSocket.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(" >> " + ex.ToString());
            }
        }
        #endregion
    }
}
